spring:
  application:
    name: bookstore
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait=: 1
        max-idle: 8
        min-idle: 0
    timeout: 300
  jpa:
    database: mysql
#    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    key-store: lulu.keystore
    key-store-password: LTY010722
    key-store-type: PKCS12
    key-alias: lulu
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
