spring:
  application:
    name: bookstore
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8443
  ssl:
    key-store: lulu.keystore
    #    key-password?! 是错的！
    key-store-password: LTY010722
    key-store-type: PKCS12
    key-alias: lulu
