package com.bookstore.backend.constant;

public enum UserServiceResponse {
    LOGIN_ADMIN,
    LOGIN_CUSTOMER,
    LOGIN_USERNAME_INVALID,
    LOGIN_PASSWORD_INVALID,
    LOGIN_NOT_FOUND,
    LOGIN_FORBIDDEN,
    REGISTER_ALL_OK,
    REGISTER_NICKNAME_INVALID,
    REGISTER_USERNAME_INVALID,
    REGISTER_PASSWORD_INVALID,
    REGISTER_DUPLICATE,
    UNKNOWN_ERROR,
}
